package configuration

const (
	CONNECTION_MYSQL  = "You have successfully connected to the Mysql database"
	CONNECTION_SQLITE = "You have successfully connected to the Sqlite database"
)

const (
	ITEM_GROUP_NONE = iota
	ITEM_GROUP_GROUND
	ITEM_GROUP_CONTAINER
	ITEM_GROUP_WEAPON
	ITEM_GROUP_AMMUNITION
	ITEM_GROUP_ARMOR
	ITEM_GROUP_RUNE
	ITEM_GROUP_TELEPORT
	ITEM_GROUP_MAGICFIELD
	ITEM_GROUP_WRITEABLE
	ITEM_GROUP_KEY
	ITEM_GROUP_SPLASH
	ITEM_GROUP_FLUID
	ITEM_GROUP_LAST
)

const (
	CLIENT_VERSION_750 = 1
	CLIENT_VERSION_755 = 2
	CLIENT_VERSION_760 = 3
)

const (
	ROOT_ATTR_VERSION = 0x01
)

const (
	ITEM_ATTR_FIRST    byte = iota + 0x10
	ITEM_ATTR_SERVERID      = ITEM_ATTR_FIRST
	ITEM_ATTR_CLIENTID
	ITEM_ATTR_NAME
	ITEM_ATTR_DESCR
	ITEM_ATTR_SPEED
	ITEM_ATTR_SLOT
	ITEM_ATTR_MAXITEMS
	ITEM_ATTR_WEIGHT
	ITEM_ATTR_WEAPON
	ITEM_ATTR_AMU
	ITEM_ATTR_ARMOR
	ITEM_ATTR_MAGLEVEL
	ITEM_ATTR_MAGFIELDTYPE
	ITEM_ATTR_WRITEABLE
	ITEM_ATTR_ROTATETO
	ITEM_ATTR_DECAY
	ITEM_ATTR_SPRITEHASH
	ITEM_ATTR_MINIMAPCOLOR
	ITEM_ATTR_07
	ITEM_ATTR_08
	ITEM_ATTR_LIGHT

	ITEM_ATTR_DECAY2
	ITEM_ATTR_WEAPON2
	ITEM_ATTR_AMU2
	ITEM_ATTR_ARMOR2
	ITEM_ATTR_WRITEABLE2
	ITEM_ATTR_LIGHT2

	ITEM_ATTR_LAST
)
